//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owlsure.EFDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usage
    {
        public int Id { get; set; }
        public Nullable<int> CounterpartyId { get; set; }
        public Nullable<double> Exposure { get; set; }
        public System.DateTime ExposureDate { get; set; }
        public string TradingLine { get; set; }
    }
}
